const sleep = (ms) => {
  return new Promise((resolve) => setTimeout(resolve, ms));
};

export async function getOrders() {
  await sleep(200);
  const order_list_data = {
    data: [
      {
        id: "1",
        order_number: "123366",
        order_status: "Livrée",
        order_amount: "100",
        order_number_of_items: "2",
        order_date: "9 Mars 2021",
        order_hour: "03h46",
        order_delivery_date: "11 Mars 2021",
        order_delivery_hour: "11h30",
        order_delivery_address: "4 rue de la grande ferme lieusaint 77127",
        dishes: [
          {
            id: "1",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livrée",
            dish_total: "50€",
          },
          {
            id: "2",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livrée",
            dish_total: "50€",
          },
        ],
      },
      {
        id: "2",
        order_number: "123367",
        order_status: "Annulée",
        order_amount: "100",
        order_date: "9 Mars 2021",
        order_hour: "03h46",
        order_number_of_items: "2",
        order_cancel_date: "11 Mars 2021",
        order_cancel_hour: "10h34",
        order_delivery_address: "4 rue de la grande ferme lieusaint 77127",
        dishes: [
          {
            id: "1",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Annulé",
            dish_total: "50 €",
          },
          {
            id: "2",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Annulé",
            dish_total: "50 €",
          },
        ],
      },
      {
        id: "3",
        order_number: "123368",
        order_status: "Livrée",
        order_amount: "70",
        order_number_of_items: "7",
        order_date: "9 Mars 2021",
        order_hour: "03h46",
        order_delivery_date: "12 Mars 2021",
        order_delivery_hour: "11h30",
        order_delivery_address: "4 rue de la grande ferme lieusaint 77127",
        dishes: [
          {
            id: "1",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livré",
            dish_total: "50 €",
          },
          {
            id: "2",
            photo:
              "http://www.fashioncooking.fr/wp-content/uploads/2010/12/IMGP1105bis1.jpg",
            dish_name: "Tchep",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "2",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livré",
            dish_total: "50 €",
          },
        ],
      },
      {
        id: "4",
        order_number: "123369",
        order_status: "Annulée",
        order_amount: "100",
        order_number_of_items: "10",
        order_date: "9 Mars 2021",
        order_hour: "03h46",
        order_cancel_date: "11 Mars 2021",
        order_cancel_hour: "10h34",
        order_delivery_address: "4 rue de la grande ferme lieusaint 77127",
        dishes: [
          {
            id: "1",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Annulé",
            dish_total: "50 €",
          },
          {
            id: "2",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Annulé",
            dish_total: "50 €",
          },
        ],
      },
      {
        id: "5",
        order_number: "123370",
        order_status: "Livrée",
        order_amount: "100",
        order_number_of_items: "10",
        order_date: "9 Mars 2021",
        order_hour: "03h46",
        order_delivery_date: "13 Mars 2021",
        order_delivery_hour: "11h30",
        order_delivery_address: "4 rue de la grande ferme lieusaint 77127",
        dishes: [
          {
            id: "1",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livré",
            dish_total: "50 €",
          },
          {
            id: "2",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa 2",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livré",
            dish_total: "50 €",
          },
          {
            id: "3",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa 3",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livré",
            dish_total: "50 €",
          },
          {
            id: "4",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa 4",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livré",
            dish_total: "50 €",
          },
          {
            id: "5",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa 5",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livré",
            dish_total: "50 €",
          },
          {
            id: "6",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa 6",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Livré",
            dish_total: "50 €",
          },
        ],
      },
      {
        id: "6",
        order_number: "123365",
        order_status: "Annulée",
        order_amount: "100",
        order_number_of_items: "10",
        order_date: "9 Mars 2021",
        order_hour: "03h46",
        order_cancel_date: "11 Mars 2021",
        order_cancel_hour: "10h34",
        order_delivery_address: "4 rue de la grande ferme lieusaint 77127",
        dishes: [
          {
            id: "1",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Annulé",
            dish_total: "50 €",
          },
          {
            id: "2",
            photo:
              "https://img-3.journaldesfemmes.fr/M_bbWpTVNekL5O_MLzQ4dyInmJU=/750x/smart/1c9fe4d4419047f18efc37134a046e5a/recipe-jdf/1001383.jpg",
            dish_name: "Poulet Yassa",
            dish_rating: "4.8/5",
            dish_unit_price: "10",
            dish_quantity: "5",
            dish_order_date: "9 Mars 2021",
            dish_order_status: "Annulé",
            dish_total: "50 €",
          },
        ],
      },
    ],
  };
  return order_list_data;
}
